### ISSUE TITLE
Is this gem maintained?

### ISSUE THREAD

**Issue by jesster2k10** [nyagato-00/predictor#45]
I was hoping to integrate this library into a new rails project I am working on but it seems like the project has been mostly abandoned. 

Are there any updates on the status of this project, considering the last commit was in 2015?

**Comment by NevilleS** [comment]
No, not actively. The math behind these predictions (Jaccard similarity) is as accurate as it was back then, but we don't have maintainers for this gem today so you'd likely want to fork it and make updates as needed.

**Comment by jesster2k10** [comment]
Okay, that's fine I assumed I would've had to fork the repository at sometimes anyways. Will new pull requests still be reviewed likewise with issues?

**Comment by nyagato-00** [comment]
@jesster2k10 
This Gem has been reopened for maintenance 🙋 .
Issues and PR are welcome ✨ .

**Comment by nyagato-00** [comment]
I've resumed maintenance, so I'll close this issue.
